from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import CardWidget, TreeWidget, PrimaryPushButton, PushButton


class Ui_ManagerWidget(object):
    def setupUi(self, ManagerWidget):
        self.ManagerWidget = ManagerWidget  # 将ManagerWidget对象设为类属性
        ManagerWidget.setObjectName("ManagerWidget")
        ManagerWidget.resize(469, 594)
        ManagerWidget.setMinimumSize(QtCore.QSize(400, 500))
        ManagerWidget.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ManagerWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CardWidget = CardWidget(ManagerWidget)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resturantWidget = TreeWidget(self.CardWidget)
        self.resturantWidget.setAllColumnsShowFocus(True)
        self.resturantWidget.setWordWrap(False)
        self.resturantWidget.setHeaderHidden(False)
        self.resturantWidget.setExpandsOnDoubleClick(True)
        self.resturantWidget.setColumnCount(1)
        self.resturantWidget.setObjectName("resturantWidget")
        self.resturantWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.resturantWidget)
        self.horizontalLayout.addWidget(self.CardWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.addRestaurantButton = PrimaryPushButton(ManagerWidget)
        self.addRestaurantButton.setObjectName("addRestaurantButton")
        self.verticalLayout_2.addWidget(self.addRestaurantButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.addCounterButton = PrimaryPushButton(ManagerWidget)
        self.addCounterButton.setObjectName("addCounterButton")
        self.verticalLayout_2.addWidget(self.addCounterButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.addDishButton = PrimaryPushButton(ManagerWidget)
        self.addDishButton.setObjectName("addDishButton")
        self.verticalLayout_2.addWidget(self.addDishButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.deleteButton = PushButton(ManagerWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_2.addWidget(self.deleteButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)

        self.retranslateUi(ManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(ManagerWidget)
        self.resturantWidget.headerItem().setText(0, "餐厅")
        self.resturantWidget.expandAll()

    def retranslateUi(self, ManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        ManagerWidget.setWindowTitle(_translate("ManagerWidget", "Form"))
        self.addRestaurantButton.setText(_translate("ManagerWidget", "添加餐厅"))
        self.addCounterButton.setText(_translate("ManagerWidget", "添加柜台"))
        self.addDishButton.setText(_translate("ManagerWidget", "添加菜品"))
        self.deleteButton.setText(_translate("ManagerWidget", "删除"))
