# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWidget(object):
    def setupUi(self, RegisterWidget):
        RegisterWidget.setObjectName("RegisterWidget")
        RegisterWidget.resize(359, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegisterWidget.sizePolicy().hasHeightForWidth())
        RegisterWidget.setSizePolicy(sizePolicy)
        RegisterWidget.setMinimumSize(QtCore.QSize(359, 520))
        RegisterWidget.setMaximumSize(QtCore.QSize(359, 520))
        RegisterWidget.setStyleSheet("")
        self.Widget = QtWidgets.QWidget(RegisterWidget)
        self.Widget.setGeometry(QtCore.QRect(0, 0, 360, 524))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget.sizePolicy().hasHeightForWidth())
        self.Widget.setSizePolicy(sizePolicy)
        self.Widget.setMinimumSize(QtCore.QSize(340, 0))
        self.Widget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.Widget.setStyleSheet("QLabel{\n"
"    font: 13px \'Microsoft YaHei\'\n"
"}")
        self.Widget.setObjectName("Widget")
        self.ImageLable = QtWidgets.QLabel(self.Widget)
        self.ImageLable.setEnabled(True)
        self.ImageLable.setGeometry(QtCore.QRect(130, 30, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLable.sizePolicy().hasHeightForWidth())
        self.ImageLable.setSizePolicy(sizePolicy)
        self.ImageLable.setMinimumSize(QtCore.QSize(100, 100))
        self.ImageLable.setMaximumSize(QtCore.QSize(100, 100))
        self.ImageLable.setText("")
        self.ImageLable.setPixmap(QtGui.QPixmap(":/login.png"))
        self.ImageLable.setScaledContents(True)
        self.ImageLable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ImageLable.setObjectName("ImageLable")
        self.label_5 = BodyLabel(self.Widget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 39, 18))
        self.label_5.setScaledContents(False)
        self.label_5.setProperty("pixelFontSize", 13)
        self.label_5.setObjectName("label_5")
        self.userName = LineEdit(self.Widget)
        self.userName.setGeometry(QtCore.QRect(20, 160, 321, 40))
        self.userName.setMinimumSize(QtCore.QSize(0, 40))
        self.userName.setClearButtonEnabled(True)
        self.userName.setObjectName("userName")
        self.label_6 = BodyLabel(self.Widget)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 26, 18))
        self.label_6.setObjectName("label_6")
        self.password = LineEdit(self.Widget)
        self.password.setGeometry(QtCore.QRect(20, 320, 321, 40))
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.RegisterButton = PrimaryPushButton(self.Widget)
        self.RegisterButton.setGeometry(QtCore.QRect(20, 460, 321, 32))
        self.RegisterButton.setObjectName("RegisterButton")
        self.label_7 = BodyLabel(self.Widget)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 26, 18))
        self.label_7.setScaledContents(False)
        self.label_7.setProperty("pixelFontSize", 13)
        self.label_7.setObjectName("label_7")
        self.nickName = LineEdit(self.Widget)
        self.nickName.setGeometry(QtCore.QRect(20, 240, 321, 40))
        self.nickName.setMinimumSize(QtCore.QSize(0, 40))
        self.nickName.setClearButtonEnabled(True)
        self.nickName.setObjectName("nickName")
        self.label_8 = BodyLabel(self.Widget)
        self.label_8.setGeometry(QtCore.QRect(20, 370, 52, 18))
        self.label_8.setObjectName("label_8")
        self.password_2 = LineEdit(self.Widget)
        self.password_2.setGeometry(QtCore.QRect(20, 400, 321, 40))
        self.password_2.setMinimumSize(QtCore.QSize(0, 40))
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setClearButtonEnabled(True)
        self.password_2.setObjectName("password_2")

        self.retranslateUi(RegisterWidget)
        QtCore.QMetaObject.connectSlotsByName(RegisterWidget)

    def retranslateUi(self, RegisterWidget):
        _translate = QtCore.QCoreApplication.translate
        RegisterWidget.setWindowTitle(_translate("RegisterWidget", "Form"))
        self.label_5.setText(_translate("RegisterWidget", "用户名"))
        self.userName.setPlaceholderText(_translate("RegisterWidget", "example@example.com"))
        self.label_6.setText(_translate("RegisterWidget", "密码"))
        self.password.setPlaceholderText(_translate("RegisterWidget", "••••••••••••"))
        self.RegisterButton.setText(_translate("RegisterWidget", "注册"))
        self.label_7.setText(_translate("RegisterWidget", "昵称"))
        self.nickName.setPlaceholderText(_translate("RegisterWidget", "Free to yourself"))
        self.label_8.setText(_translate("RegisterWidget", "确认密码"))
        self.password_2.setPlaceholderText(_translate("RegisterWidget", "••••••••••••"))
from qfluentwidgets import BodyLabel, LineEdit, PrimaryPushButton
from picture_set import pic_rc
