# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userWidget(object):
    def setupUi(self, userWidget):
        userWidget.setObjectName("userWidget")
        userWidget.resize(469, 594)
        userWidget.setMinimumSize(QtCore.QSize(400, 500))
        userWidget.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(userWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CardWidget = CardWidget(userWidget)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resturantWidget = TreeWidget(self.CardWidget)
        self.resturantWidget.setAllColumnsShowFocus(True)
        self.resturantWidget.setWordWrap(False)
        self.resturantWidget.setHeaderHidden(False)
        self.resturantWidget.setExpandsOnDoubleClick(True)
        self.resturantWidget.setColumnCount(1)
        self.resturantWidget.setObjectName("resturantWidget")
        self.resturantWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.resturantWidget)
        self.horizontalLayout.addWidget(self.CardWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.BodyLabel = BodyLabel(userWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_2.addWidget(self.BodyLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.PrimaryPushButton = PrimaryPushButton(userWidget)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout_2.addWidget(self.PrimaryPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)

        self.retranslateUi(userWidget)
        QtCore.QMetaObject.connectSlotsByName(userWidget)
        self.resturantWidget.headerItem().setText(0, "餐厅")
    def retranslateUi(self, userWidget):
        _translate = QtCore.QCoreApplication.translate
        userWidget.setWindowTitle(_translate("userWidget", "Form"))
        self.BodyLabel.setText(_translate("userWidget", " 总数："))
        self.PrimaryPushButton.setText(_translate("userWidget", "查看详情"))
from qfluentwidgets import BodyLabel, CardWidget, PrimaryPushButton, TreeWidget
from picture_set import pic_rc
