# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MySearchWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWidget(object):
    def setupUi(self, SearchWidget):
        SearchWidget.setObjectName("SearchWidget")
        SearchWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(SearchWidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.verticalLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(SearchWidget)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout.addWidget(self.searchButton)
        self.resultListWidget = QtWidgets.QListWidget(SearchWidget)
        self.resultListWidget.setObjectName("resultListWidget")
        self.verticalLayout.addWidget(self.resultListWidget)

        self.retranslateUi(SearchWidget)
        QtCore.QMetaObject.connectSlotsByName(SearchWidget)

    def retranslateUi(self, SearchWidget):
        _translate = QtCore.QCoreApplication.translate
        SearchWidget.setWindowTitle(_translate("SearchWidget", "SearchWidget"))
        self.searchButton.setText(_translate("SearchWidget", "Search"))
