# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWidget(object):
    def setupUi(self, SearchWidget):
        SearchWidget.setObjectName("SearchWidget")
        SearchWidget.resize(462, 572)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SearchWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CardWidget = CardWidget(SearchWidget)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SearchLineEdit = SearchLineEdit(self.CardWidget)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.verticalLayout.addWidget(self.SearchLineEdit)
        self.TableWidget = TableWidget(self.CardWidget)
        self.TableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(4)
        self.TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.TableWidget)
        self.verticalLayout_2.addWidget(self.CardWidget)

        self.retranslateUi(SearchWidget)
        QtCore.QMetaObject.connectSlotsByName(SearchWidget)

    def retranslateUi(self, SearchWidget):
        _translate = QtCore.QCoreApplication.translate
        SearchWidget.setWindowTitle(_translate("SearchWidget", "Form"))
        item = self.TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchWidget", "菜品"))
        item = self.TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchWidget", "餐厅"))
        item = self.TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchWidget", "柜台"))
        item = self.TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchWidget", "时间"))
from qfluentwidgets import CardWidget, SearchLineEdit, TableWidget
