# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(701, 534)
        LoginWidget.setMinimumSize(QtCore.QSize(400, 500))
        LoginWidget.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(LoginWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(LoginWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(360, 0))
        self.widget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.widget.setStyleSheet("QLabel{\n"
"    font: 13px \'Microsoft YaHei\'\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.ImageLable = QtWidgets.QLabel(self.widget)
        self.ImageLable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLable.sizePolicy().hasHeightForWidth())
        self.ImageLable.setSizePolicy(sizePolicy)
        self.ImageLable.setMinimumSize(QtCore.QSize(100, 100))
        self.ImageLable.setMaximumSize(QtCore.QSize(100, 100))
        self.ImageLable.setText("")
        self.ImageLable.setPixmap(QtGui.QPixmap(":/login.png"))
        self.ImageLable.setScaledContents(True)
        self.ImageLable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ImageLable.setObjectName("ImageLable")
        self.verticalLayout_2.addWidget(self.ImageLable, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_5 = BodyLabel(self.widget)
        self.label_5.setScaledContents(False)
        self.label_5.setProperty("pixelFontSize", 13)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.userName = LineEdit(self.widget)
        self.userName.setMinimumSize(QtCore.QSize(0, 40))
        self.userName.setClearButtonEnabled(True)
        self.userName.setObjectName("userName")
        self.verticalLayout_2.addWidget(self.userName)
        self.label_6 = BodyLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.password = LineEdit(self.widget)
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.LoginButton = PrimaryPushButton(self.widget)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout_2.addWidget(self.LoginButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.RegisterButton = HyperlinkButton(self.widget)
        self.RegisterButton.setObjectName("RegisterButton")
        self.verticalLayout_2.addWidget(self.RegisterButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "Form"))
        self.label_5.setText(_translate("LoginWidget", "用户名"))
        self.userName.setPlaceholderText(_translate("LoginWidget", "example@example.com"))
        self.label_6.setText(_translate("LoginWidget", "密码"))
        self.password.setPlaceholderText(_translate("LoginWidget", "••••••••••••"))
        self.LoginButton.setText(_translate("LoginWidget", "登录"))
        self.RegisterButton.setText(_translate("LoginWidget", "注册新用户"))
from qfluentwidgets import BodyLabel, HyperlinkButton, LineEdit, PrimaryPushButton
from picture_set import pic_rc
