# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History_item_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History_item(object):
    def setupUi(self, History_item):
        History_item.setObjectName("History_item")
        History_item.resize(820, 135)
        self.CardWidget = CardWidget(History_item)
        self.CardWidget.setGeometry(QtCore.QRect(5, 0, 811, 131))
        self.CardWidget.setObjectName("CardWidget")
        self.layoutWidget = QtWidgets.QWidget(self.CardWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 7, 661, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImageLabel = ImageLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLabel.sizePolicy().hasHeightForWidth())
        self.ImageLabel.setSizePolicy(sizePolicy)
        self.ImageLabel.setMinimumSize(QtCore.QSize(96, 96))
        self.ImageLabel.setMaximumSize(QtCore.QSize(96, 96))
        self.ImageLabel.setPixmap(QtGui.QPixmap(":/Dishes_96x96/九转大肠_96x96.jpg"))
        self.ImageLabel.setScaledContents(True)
        self.ImageLabel.setObjectName("ImageLabel")
        self.horizontalLayout_2.addWidget(self.ImageLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dish_name = BodyLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dish_name.setFont(font)
        self.dish_name.setObjectName("dish_name")
        self.horizontalLayout.addWidget(self.dish_name)
        self.dish_type = BodyLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dish_type.setFont(font)
        self.dish_type.setObjectName("dish_type")
        self.horizontalLayout.addWidget(self.dish_type)
        self.restaurant_name = BodyLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.restaurant_name.setFont(font)
        self.restaurant_name.setObjectName("restaurant_name")
        self.horizontalLayout.addWidget(self.restaurant_name)
        self.counter_name = BodyLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.counter_name.setFont(font)
        self.counter_name.setObjectName("counter_name")
        self.horizontalLayout.addWidget(self.counter_name)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.CardWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(700, 40, 101, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deleteButton = PushButton(self.layoutWidget1)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.history_time = BodyLabel(self.layoutWidget1)
        self.history_time.setAlignment(QtCore.Qt.AlignCenter)
        self.history_time.setObjectName("history_time")
        self.verticalLayout.addWidget(self.history_time)

        self.retranslateUi(History_item)
        QtCore.QMetaObject.connectSlotsByName(History_item)

    def retranslateUi(self, History_item):
        _translate = QtCore.QCoreApplication.translate
        History_item.setWindowTitle(_translate("History_item", "Form"))
        self.dish_name.setText(_translate("History_item", "鱼香肉丝"))
        self.dish_type.setText(_translate("History_item", "类型A"))
        self.restaurant_name.setText(_translate("History_item", "餐厅A"))
        self.counter_name.setText(_translate("History_item", "柜台A"))
        self.deleteButton.setText(_translate("History_item", "删除历史"))
        self.history_time.setText(_translate("History_item", "2023-07-21"))
from qfluentwidgets import BodyLabel, CardWidget, ImageLabel, PushButton
from picture_set import pic_rc
