# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyHistoryWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyHistoryWidget(object):
    def setupUi(self, MyHistoryWidget):
        MyHistoryWidget.setObjectName("MyHistoryWidget")
        MyHistoryWidget.resize(1032, 665)

        self.retranslateUi(MyHistoryWidget)
        QtCore.QMetaObject.connectSlotsByName(MyHistoryWidget)

    def retranslateUi(self, MyHistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        MyHistoryWidget.setWindowTitle(_translate("MyHistoryWidget", "Form"))
