# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyHistoryWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyHistoryWidget(object):
    def setupUi(self, MyHistoryWidget):
        MyHistoryWidget.setObjectName("MyHistoryWidget")
        MyHistoryWidget.resize(1032, 665)
        self.layoutWidget = QtWidgets.QWidget(MyHistoryWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 979, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(838, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TitleLabel = TitleLabel(self.layoutWidget)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TitleLabel.setProperty("pixelFontSize", 32)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.MyCardWidget = CardWidget(MyHistoryWidget)
        self.MyCardWidget.setGeometry(QtCore.QRect(20, 120, 981, 501))
        self.MyCardWidget.setStyleSheet("")
        self.MyCardWidget.setObjectName("MyCardWidget")
        self.scroll_area = ScrollArea(self.MyCardWidget)
        self.scroll_area.setGeometry(QtCore.QRect(10, 10, 851, 481))
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.clearButton = PushButton(self.MyCardWidget)
        self.clearButton.setGeometry(QtCore.QRect(870, 70, 102, 32))
        self.clearButton.setObjectName("clearButton")
        self.searchButton = PrimaryPushButton(self.MyCardWidget)
        self.searchButton.setGeometry(QtCore.QRect(870, 10, 101, 32))
        self.searchButton.setObjectName("searchButton")

        self.retranslateUi(MyHistoryWidget)
        QtCore.QMetaObject.connectSlotsByName(MyHistoryWidget)

    def retranslateUi(self, MyHistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        MyHistoryWidget.setWindowTitle(_translate("MyHistoryWidget", "Form"))
        self.TitleLabel.setText(_translate("MyHistoryWidget", "美食记录"))
        self.clearButton.setText(_translate("MyHistoryWidget", "清空历史"))
        self.searchButton.setText(_translate("MyHistoryWidget", "查询历史"))
from qfluentwidgets import CardWidget, PrimaryPushButton, PushButton, ScrollArea, TitleLabel
