# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyFavoriteWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyFavoriteWidget(object):
    def setupUi(self, MyFavoriteWidget):
        MyFavoriteWidget.setObjectName("MyFavoriteWidget")
        MyFavoriteWidget.resize(1032, 663)

        self.retranslateUi(MyFavoriteWidget)
        QtCore.QMetaObject.connectSlotsByName(MyFavoriteWidget)

    def retranslateUi(self, MyFavoriteWidget):
        _translate = QtCore.QCoreApplication.translate
        MyFavoriteWidget.setWindowTitle(_translate("MyFavoriteWidget", "Form"))
